# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_liza.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 751)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(216, 216, 255);\n"
"gridline-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mino = QtWidgets.QLabel(self.centralwidget)
        self.mino.setGeometry(QtCore.QRect(110, 40, 791, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mino.setFont(font)
        self.mino.setMouseTracking(False)
        self.mino.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border-color: rgb(255, 85, 255);")
        self.mino.setObjectName("min")
        self.chet = QtWidgets.QPushButton(self.centralwidget)
        self.chet.setGeometry(QtCore.QRect(260, 390, 451, 91))
        self.chet.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(158, 255, 255);")
        self.chet.setObjectName("chet")
        self.num1 = QtWidgets.QPushButton(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(250, 160, 461, 81))
        self.num1.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(219, 255, 254);")
        self.num1.setObjectName("num1")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(260, 270, 81, 81))
        self.plus.setMaximumSize(QtCore.QSize(81, 16777215))
        self.plus.setStyleSheet("background-color: rgb(160, 128, 255);\n"
"gridline-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(380, 270, 81, 81))
        self.minus.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.minus.setObjectName("minus")
        self.umnog = QtWidgets.QPushButton(self.centralwidget)
        self.umnog.setGeometry(QtCore.QRect(500, 270, 81, 81))
        self.umnog.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.umnog.setObjectName("umnog")
        self.delite = QtWidgets.QPushButton(self.centralwidget)
        self.delite.setGeometry(QtCore.QRect(620, 270, 81, 81))
        self.delite.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.delite.setObjectName("delite")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(120, 160, 93, 91))
        self.one.setStyleSheet("background-color: rgb(112, 0, 168);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.one.setObjectName("one")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(120, 390, 93, 91))
        self.three.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(139, 0, 208);")
        self.three.setObjectName("three")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(370, 500, 93, 91))
        self.five.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(157, 0, 235);")
        self.five.setObjectName("five")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(120, 280, 93, 91))
        self.two.setStyleSheet("background-color: rgb(127, 0, 191);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.two.setObjectName("two")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(240, 500, 93, 91))
        self.four.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(151, 0, 226);")
        self.four.setObjectName("four")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(500, 500, 93, 91))
        self.six.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(200, 2, 239);")
        self.six.setObjectName("six")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(750, 380, 93, 91))
        self.eight.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(209, 69, 209);")
        self.eight.setObjectName("eight")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(630, 500, 93, 91))
        self.seven.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(200, 0, 200);")
        self.seven.setObjectName("seven")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(750, 270, 93, 91))
        self.nine.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 255);")
        self.nine.setObjectName("nine")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(750, 150, 93, 91))
        self.zero.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 255);")
        self.zero.setObjectName("zero")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 500, 111, 111))
        self.label.setStyleSheet("background-color: rgb(35, 219, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 490, 111, 111))
        self.label_2.setStyleSheet("background-color: rgb(35, 219, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 540, 711, 20))
        self.label_3.setStyleSheet("background-color: rgb(35, 219, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 190, 551, 21))
        self.label_4.setStyleSheet("background-color: rgb(35, 219, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 300, 551, 21))
        self.label_5.setStyleSheet("background-color: rgb(35, 219, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 410, 551, 21))
        self.label_6.setStyleSheet("background-color: rgb(35, 219, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.mino.raise_()
        self.chet.raise_()
        self.num1.raise_()
        self.plus.raise_()
        self.minus.raise_()
        self.umnog.raise_()
        self.one.raise_()
        self.three.raise_()
        self.five.raise_()
        self.two.raise_()
        self.delite.raise_()
        self.four.raise_()
        self.six.raise_()
        self.eight.raise_()
        self.seven.raise_()
        self.nine.raise_()
        self.zero.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.calfun()
        self.ravnore = False

    def calfun(self):
        self.nine.clicked.connect(lambda:self.wrine_n(self.nine.text()))
        self.zero.clicked.connect(lambda: self.wrine_n(self.zero.text()))
        self.one.clicked.connect(lambda: self.wrine_n(self.one.text()))
        self.two.clicked.connect(lambda: self.wrine_n(self.two.text()))
        self.three.clicked.connect(lambda: self.wrine_n(self.three.text()))
        self.four.clicked.connect(lambda: self.wrine_n(self.four.text()))
        self.five.clicked.connect(lambda: self.wrine_n(self.five.text()))
        self.six.clicked.connect(lambda: self.wrine_n(self.six.text()))
        self.seven.clicked.connect(lambda: self.wrine_n(self.seven.text()))
        self.eight.clicked.connect(lambda: self.wrine_n(self.eight.text()))
        self.plus.clicked.connect(lambda: self.wrine_n(self.plus.text()))
        self.delite.clicked.connect(lambda: self.wrine_n(self.delite.text()))
        self.minus.clicked.connect(lambda: self.wrine_n(self.minus.text()))
        self.umnog.clicked.connect(lambda: self.wrine_n(self.umnog.text()))
        self.chet.clicked.connect(self.resultn)


    def wrine_n(self,numbers):
        if self.mino.text() == "0" or self.ravnore:
                self.mino.setText(numbers)
                self.ravnore = False
        else:
                self.mino.setText(self.mino.text()+numbers)

    def resultn(self):
        res = eval(self.mino.text())
        self.mino.setText("= " + str(res))
        self.ravnore = True





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mino.setText(_translate("MainWindow", "0"))
        self.chet.setText(_translate("MainWindow", "Считать."))
        self.num1.setText(_translate("MainWindow", "Ввести число:"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.umnog.setText(_translate("MainWindow", "*"))
        self.one.setText(_translate("MainWindow", "1"))
        self.three.setText(_translate("MainWindow", "3"))
        self.five.setText(_translate("MainWindow", "5"))
        self.two.setText(_translate("MainWindow", "2"))
        self.four.setText(_translate("MainWindow", "4"))
        self.six.setText(_translate("MainWindow", "6"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.delite.setText(_translate("MainWindow", "//"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
